name: UAT CI

on:
  pull_request:
    branches: [ master ]

  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: |
          ./gradlew assembleDebug